# ==============================
# MapTree - Configurações Locais
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5433/maptree_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.token=stoken_secreto_teste_sabe_producaooooooa

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true